title: Rakitine Family Stories
email: oleg@rakitine.com
description: >- # this means to ignore newlines until "baseurl:"
  History of Rakitine clan.
  One story at a time
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ovr
github_username:  orakitine
# gitlab_username:  pages

# Build settings
theme: jekyll-theme-slate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
